# FACAD data nums: 92342

includes:
- configs/models/alignment/defaults.yaml

model_config:
  cm_shared_transformer:
    image_encoder:
      type: torchvision_resnet
      params:
        name: resnet50
        pretrained: true
        zero_init_residual: false

scheduler:
  type: multi_step
  params:
    use_warmup: false
    lr_steps:
    - 43260
    - 86520
    lr_ratio: 0.1
    warmup_iterations: 1442
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 1e-4
    eps: 1e-8

evaluation:
  metrics:
  - r@1_rev_retrieval
  - r@5_rev_retrieval
  - r@10_rev_retrieval

training:
  experiment_name: cm_shared_transformer_facad
  batch_size: 64
  lr_scheduler: true
  max_updates: 115360
  # log_interval: 1
  checkpoint_interval: 1442
  evaluation_interval: 1442
  wandb:
    enabled: true

run_type: train_val
