# FashionIQ data nums: 18000

includes:
- configs/models/fashionvil/defaults.yaml

dataset_config:
  fashioniq:
    use_images: false
    use_features: true

model_config:
  fashionvil:
    bert_model_name: bert-base-uncased
    training_head_type: composition
    bypass_transformer: false
    losses:
      - type: bbc_loss

scheduler:
  type: multi_step
  params:
    use_warmup: true
    lr_steps:
    - 16860
    - 28100
    lr_ratio: 0.1
    warmup_iterations: 2810
    warmup_factor: 0.25

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8
    weight_decay: 1e-4

evaluation:
  metrics:
    - r@k_fashioniq

training:
  experiment_name: fashionvil_composition_fashioniq_pretrain_itc_itm_mlm_mpfc
  batch_size: 32
  lr_scheduler: true
  max_updates: 44960
  log_interval: 10
  checkpoint_interval: 5620
  evaluation_interval: 562
  early_stop:
    criteria: fashioniq/r@k_fashioniq/avg
    minimize: false
  wandb:
    enabled: true

run_type: train_val

checkpoint:
  resume_pretrained: true
  resume_file: save/fashionvil_pretrain_itc_itm_mlm_mpfc/best.ckpt
  pretrained_state_mapping:
    model.bert: model.bert
